# Default build settings

language: c++
compiler: g++
os: linux
fast_finish: true

branches:
    only:
        - master
        - stable  
        - dmitri-dev

install: make tests

script: tests/ALL_TESTS
