language: c++

compiler:
    - g++
os: linux

before_install:
    - make test

jobs:
    include:
            - stage: test
            - script: tests/test

notifications:
    slack: frupal-dev:EqKuho9NXtDZzAyzMpRTr1pM
